import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // tutorials 폴더 기준
    },
  ],
};

export default sidebars;
